server:
  port: 8080

spring:
  # MYSQL data source configuration. No need to explain too much.
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 968717

mybatis:
  # Set the xml configuration file address for mybatis.
  # config-location: "classpath:mybatis/mybatis-config.xml"

  # Loads all files in the 'mapper' directory (regardless of directory hierarchy) with names ending in '-mapper.xml'.
  mapper-locations:
    - "classpath:mapper/*.xml"